### ISSUE TITLE
Can't auth : CORS problem in Firefox

### ISSUE THREAD

**Issue by ToXinE** [sharkykh/tppm#15]
![trakt_problem](https://user-images.githubusercontent.com/6205053/91541416-9ff1c700-e91c-11ea-8b8d-1749ce2d9b70.gif)

**Comment by sharkykh** [comment]
Yes, spotted this issue earlier today.
Considering this app has worked for the last year, and I've changed nothing, it's seems like a Trakt issue.
I've already reported this to Trakt, waiting for a response.

**Comment by MohandL3G** [comment]
I have this issue, and I'm using Edge (Chromium)

**Comment by sharkykh** [comment]
Seems like it's working again right now. Still waiting for confirmation from Trakt,
but it is working.
