### ISSUE TITLE
[Bug] Web tool is not working properly

### ISSUE THREAD

**Issue by ShibajiCh** [sharkykh/tppm#33]
Hi @sharkykh,

First of all thanks for the amazing "Trakt Playback Progress Manager" web tool. I've been using it for quite some time.

However, since last few days it's not working properly. I've 2 Trakt accounts. For 1 account it's not fetching any data and for the other even though it's fetching data I'm not able to remove any progress data using the tool. It looks like the issue is quite widespread as well. See here in Reddit:

https://www.reddit.com/r/Addons4Kodi/comments/u8ruf3/anyone_facing_trakt_errors_does_this_tool_work/?utm_medium=android_app&utm_source=share

Could you please look into the issue and kindly advise?

Thanks and Regards,
ShibajiCh.

**Comment by xyzfre** [comment]
I've been having the same issue for a couple days as well I'm not able to remove any progress data using the tool

**Comment by sharkykh** [comment]
Currently waiting for [a response from Trakt](https://github.com/trakt/api-help/discussions/341). It's not something I'm able to fix on my own.

**Comment by sharkykh** [comment]
Fixed by a Trakt developer.

**Comment by ShibajiCh** [comment]
Hi @sharkykh,

Thank you!

Thanks and Regards,
ShibajiCh.

**Comment by sharkykh** [comment]
@dannymichel 
Not really, but [it was related to cache](https://github.com/trakt/api-help/discussions/341#discussioncomment-2650155).
