### ISSUE TITLE
Other trakt tools ?

### ISSUE THREAD

**Issue by Arthur1967** [sharkykh/tppm#37]
I'm glad I found this working good for me on 19.4 is there any other tools you know of or have for trakt Thanks again

**Comment by sharkykh** [comment]
The only thing I really use is [iamkroot/trakt-scrobbler](https://github.com/iamkroot/trakt-scrobbler) to scrobble to Trakt.
Try asking on [reddit](https://www.reddit.com/r/trakt/)?

**Comment by Arthur1967** [comment]
OK thank you I was looking for a way to get rid of all the bookmarks have a good day
