### ISSUE TITLE
404 Error - There isn't a Github pages site here

### ISSUE THREAD

**Issue by ZelKami** [sharkykh/tppm#46]
The link to the WebApp doesn't work anymore as there is only a 404 error displayed

**Comment by Arthur1967** [comment]
Is there anyway I can use it for kodi are used to use that all the time. Thanks.

**Comment by TapMeDead** [comment]
Same problem today, I use this page almost daily because Seren sucks at remembering to scroll forward to the time I was at.

**Comment by sharkykh** [comment]
Site is back up now.
